version: "3"
services:
  app:
   build: .
   restart: always
   env_file:
    - "./.env"
   command: npm run dev
   ports:
    - 3000:3000
   depends_on:
    - postgres
   volumes:
    - .:/smart-recharge-api
    - /smart-recharge-api/node_modules

  postgres:
    restart: always
    image: postgres
    ports:
      - 7000:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
     - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
